"""Roadmap content — stages 10–12. Schema: see roadmap_content/__init__.py."""

STAGES = [
    {
        "n": "10", "name": "MLOps & Deployment", "track": "Production & Security", "icon": "🚢",
        "tagline": "Package, ship and run models reliably and securely.",
        "handoff": "A deployed, network-exposed system — exactly what AI Cybersecurity (stage 11) attacks and defends.",
        "topics": [
            {
                "id": "fastapi", "name": "Model serving (FastAPI)",
                "oneliner": "Wrap a model in an HTTP API with validated inputs so any app, agent or UI can use it.",
                "real_world": [
                    ["FastAPI", "lists Microsoft, Uber and Netflix among its users; Netflix's open-source Dispatch is built on it."],
                    ["Model APIs", "the Gemini, OpenAI and Azure OpenAI APIs are themselves model-serving endpoints."],
                ],
                "analogy": "A restaurant counter: customers never enter the kitchen, they order from a fixed menu.",
                "math": "latency budget: p95(response time) ≤ SLO;  throughput = requests / second",
                "code": "@app.post('/score')\ndef score(bank: BankRatios):\n    p = model.predict_proba(to_frame(bank))[0, 1]\n    return {'predicted_failure_probability': p}",
                "in_project": "backend/main.py — /score, /chat, /speech/*, /gnn/*, /security/*.",
                "security": "The API is the attack surface for model stealing and abuse — rate limits and auth matter.",
            },
            {
                "id": "docker", "name": "Containers (Docker)",
                "oneliner": "Package code, dependencies and models into an image that runs the same everywhere.",
                "real_world": [
                    ["Docker Hub", "hosts millions of public images; `docker pull` is how most software ships today."],
                    ["Hugging Face Spaces", "can run any Docker container to host ML demos."],
                ],
                "analogy": "A shipping container: the crane doesn't care what's inside; it fits every ship and truck.",
                "math": "image = ordered stack of content-addressed layers, id = sha256(content)",
                "code": "docker build -t camel-sentinel:v2.0 .\ndocker run -d -p 8501:8501 --env-file .env camel-sentinel:v2.0\ndocker push raushanranjan/camel-sentinel:v2.0",
                "in_project": "Dockerfile, docker-compose.yml; images on Docker Hub (raushanranjan/camel-sentinel) and ACR. See 🚢 Deploy & Containerize.",
                "security": "Never bake secrets into images; run as non-root.",
            },
            {
                "id": "kubernetes", "name": "Orchestration (Kubernetes)",
                "oneliner": "Run many containers across many machines with self-healing, scaling, rolling updates and service discovery.",
                "real_world": [
                    ["Google", "open-sourced Kubernetes in 2014, based on its internal Borg system."],
                    ["OpenAI (2021)", "described scaling Kubernetes clusters to 7,500 nodes for research workloads."],
                ],
                "analogy": "An air-traffic controller for containers: where each one lands, and what to do when one goes missing.",
                "math": "desired state (replicas = 3) − observed state → control loop reconciles continuously",
                "code": "kubectl apply -f deploy/k8s/camel-sentinel.yaml\nkubectl get pods -l app=camel-sentinel\nkubectl scale deployment camel-sentinel --replicas=5",
                "in_project": "deploy/k8s/camel-sentinel.yaml — 3 replicas, readiness/liveness probes, runAsNonRoot.",
                "security": "RBAC, network policies and pod security settings are the cluster's guardrails.",
            },
            {
                "id": "trivy", "name": "DevSecOps scanning (Trivy)",
                "oneliner": "Scan Dockerfiles, images and dependencies for misconfigurations, known vulnerabilities and secrets before shipping.",
                "real_world": [
                    ["GitLab", "container scanning is built on Trivy."],
                    ["Log4Shell (2021)", "a single vulnerable Java library exposed huge numbers of systems — why dependency scanning is routine."],
                ],
                "analogy": "Airport security for software: bags are scanned before they board, not after take-off.",
                "math": "risk = likelihood × impact; CVSS severity score 0–10 prioritises fixes",
                "code": "docker run --rm -v \"$PWD:/scan\" aquasec/trivy config /scan\ndocker run --rm aquasec/trivy image raushanranjan/camel-sentinel:v2.0",
                "in_project": "Real scan: our Dockerfile passes 27/27 checks; deploy/Dockerfile.naive fails 3 (root user, :latest, no healthcheck).",
                "security": "Scanners miss logic flaws — Trivy didn't flag `COPY . .` copying .env.",
            },
            {
                "id": "secrets", "name": "Secrets management",
                "oneliner": "Keep keys and passwords out of code and images; inject them at run time from a vault, and rotate them.",
                "real_world": [
                    ["Uber (2016)", "attackers found AWS credentials in a private GitHub repository and accessed data on 57 million users."],
                    ["Tools", "HashiCorp Vault, Azure Key Vault and AWS Secrets Manager are the standard stores."],
                ],
                "analogy": "A hotel key card issued at check-in and deactivated at checkout — never printed on the room door.",
                "math": "blast radius ∝ (secret lifetime × scope of access)",
                "code": "# never: ENV AZURE_OPENAI_KEY=sk-...\ndocker run --env-file .env camel-sentinel:v2.0          # local\naz containerapp create ... --secrets aoai-key=<key>      # cloud",
                "in_project": ".env excluded by .dockerignore; keys passed with --env-file / Container Apps secretref.",
                "security": "Leaked keys are the most common cloud breach root cause — scan repos and images for them.",
            },
            {
                "id": "mtls", "name": "TLS & mutual TLS",
                "oneliner": "TLS encrypts traffic and proves the server's identity; mTLS makes the client prove its identity too.",
                "real_world": [
                    ["Service meshes", "Istio and Linkerd can enforce mTLS between every service automatically."],
                    ["Google BeyondCorp", "a zero-trust model where every request is authenticated, not just those from outside."],
                ],
                "analogy": "Both people at a meeting show ID badges before talking, not just the host.",
                "math": "handshake: verify cert chain → CA, check SAN = hostname; mTLS repeats this for the client certificate",
                "code": "openssl req -x509 -newkey rsa:2048 -keyout ca.key -out ca.crt -days 365 -nodes\nuvicorn main:app --ssl-keyfile server.key --ssl-certfile server.crt --ssl-ca-certs ca.crt",
                "in_project": "Azure Container Apps ingress provides HTTPS automatically; mTLS is described on the Deploy page.",
                "security": "Stops a stolen API key alone from being enough to call internal services.",
            },
        ],
    },
    {
        "n": "11", "name": "AI Cybersecurity", "track": "Production & Security", "icon": "🛡️",
        "tagline": "Threat-model AI systems, attack them, and defend them — with AI on both sides.",
        "handoff": "Security findings feed back into every earlier stage: data validation, model hardening, API controls.",
        "topics": [
            {
                "id": "stride", "name": "STRIDE threat modelling",
                "oneliner": "For every component ask: Spoofing, Tampering, Repudiation, Information disclosure, Denial of service, Elevation of privilege?",
                "real_world": [
                    ["Microsoft SDL", "STRIDE came from Microsoft's Security Development Lifecycle; the free Microsoft Threat Modeling Tool uses it."],
                ],
                "analogy": "Walking around your house asking, for every door and window: how could someone get in, and what would they take?",
                "math": "coverage matrix: components × {S,T,R,I,D,E} → threats + mitigations",
                "code": "from camel_sentinel.security.threat_model import threat_model\ntm = threat_model()\n[t for t in tm['stride'] if t['component'] == 'llm']",
                "in_project": "AI Security Lab → Threat map: click any component of CAMEL Sentinel to see its STRIDE threats.",
                "security": "Threat modelling is done before building — and updated with every new feature.",
            },
            {
                "id": "atlas", "name": "MITRE ATLAS",
                "oneliner": "An ATT&CK-style knowledge base of real adversary tactics and techniques against AI systems, with case studies.",
                "real_world": [
                    ["ATLAS case studies", "include the 2019 bypass of an AI malware detector (Cylance) and many LLM prompt-injection incidents."],
                    ["Industry", "security teams map AI red-team findings to ATLAS IDs, just as they map classic attacks to ATT&CK."],
                ],
                "analogy": "A field guide to predators: what each one looks like, how it hunts, and how to protect against it.",
                "math": "tactic (the why) → technique (the how), e.g. Exfiltration → AML.T0024.002 Extract ML Model",
                "code": "ATLAS = {'prompt_injection': 'AML.T0051', 'model_extraction': 'AML.T0024.002',\n         'poisoning': 'AML.T0020', 'evasion': 'AML.T0015'}",
                "in_project": "Every AI Security Lab section is tagged with its ATLAS technique IDs.",
                "security": "A shared vocabulary between data scientists and security teams.",
            },
            {
                "id": "model_stealing", "name": "Model stealing",
                "oneliner": "Reconstruct a model's behaviour (or parts of its weights) purely by querying its API.",
                "real_world": [
                    ["Tramèr et al. (2016)", "extracted models from BigML and Amazon Machine Learning prediction APIs."],
                    ["Carlini et al. (2024)", "'Stealing Part of a Production Language Model' recovered the final projection layer of OpenAI models via the API; OpenAI changed its API in response."],
                ],
                "analogy": "Recreating a secret recipe by ordering the dish many times with small changes and tasting each one.",
                "math": "attacker fits f̂ = argmin Σ L(f̂(xᵢ), f(xᵢ)) over queried xᵢ; fidelity = agreement(f̂, f) on real data",
                "code": "X_q = random_ratios(n=5000)\ny_q = api_score(X_q)                       # victim's answers\nsurrogate = HistGradientBoostingRegressor().fit(X_q, y_q)",
                "in_project": "AI Security Lab → Model stealing: attacks /score and compares output-hardening, rate limits and stream detection.",
                "security": "ATLAS AML.T0040 + AML.T0024.002.",
            },
            {
                "id": "deepfakes", "name": "Deepfake detection",
                "oneliner": "Detect synthetic voices, faces and videos — and, more importantly, design processes that don't rely on detection alone.",
                "real_world": [
                    ["Arup (2024)", "lost about US$25 million after an employee joined a video call with deepfaked executives."],
                    ["UK energy firm (2019)", "wired €220,000 after a phone call imitating its parent company's CEO's voice."],
                    ["Provenance", "Google DeepMind's SynthID watermarks AI-generated content; C2PA Content Credentials attach tamper-evident provenance."],
                ],
                "analogy": "A forged signature can fool the eye; a callback to a known number can't be forged in the same way.",
                "math": "jitter = mean|Tᵢ − Tᵢ₋₁| / mean(T)  (pitch-period variability; humans ≈ 0.5–1.5 %)",
                "code": "from camel_sentinel.security.deepfake import run_deepfake_lab\nrun_deepfake_lab('clone_basic')['detector']",
                "in_project": "AI Security Lab → Deepfake voice (synthetic signals) — shows a detector fooled by a newer generator.",
                "security": "Voice or video must never be the sole authorisation factor for payments.",
            },
            {
                "id": "ai_soc", "name": "AI-powered SOC",
                "oneliner": "Use ML and LLMs to triage security telemetry: cluster, rank and summarise alerts so analysts act on what matters.",
                "real_world": [
                    ["Microsoft Security Copilot", "became generally available in April 2024 to summarise incidents and guide response."],
                    ["Google Security Operations", "integrates Gemini for investigation and natural-language search."],
                ],
                "analogy": "A triage nurse in a busy emergency room: every patient is seen, the most urgent first.",
                "math": "alert priority = f(rule hits, anomaly score, asset criticality); precision@k on the analyst queue",
                "code": "from camel_sentinel.security.soc import run_soc_lab\nres = run_soc_lab()\nres['alerts'][0]['playbook']",
                "in_project": "AI Security Lab → AI SOC: 4,857 synthetic API events → 5 prioritised, ATLAS-tagged alerts.",
                "security": "The SOC's own LLM is an attack surface — log injection can target the copilot.",
            },
        ],
    },
    {
        "n": "12", "name": "Capstone: One Secured System", "track": "Production & Security", "icon": "🏁",
        "tagline": "Everything together: one integrated, explainable, deployed and defended AI system.",
        "handoff": "CAMEL Sentinel itself is the capstone — every stage above lives somewhere in this app.",
        "topics": [
            {
                "id": "architecture", "name": "End-to-end architecture",
                "oneliner": "Data → features → model → explanations → API → UI/agent → container → cloud, each part replaceable and testable.",
                "real_world": [
                    ["'Hidden Technical Debt in ML Systems' (Google, NeurIPS 2015)", "showed the model is a small box in a large system of data, config, serving and monitoring."],
                ],
                "analogy": "A relay race: every runner (component) must hand over the baton cleanly.",
                "math": "system quality ≤ min(quality of each stage) — the weakest link sets the ceiling",
                "code": "FDIC API → camel_ratios.py → HistGradientBoosting → SHAP/LIME/CF → FastAPI → Streamlit + ChatAgent → Docker → ACR/Docker Hub → Azure Container Apps",
                "in_project": "The whole repository; see docs/03_module_mapping.md for where each stage lives.",
                "security": "Each hand-over is a trust boundary — the STRIDE map marks them.",
            },
            {
                "id": "secure_by_design", "name": "Security by design",
                "oneliner": "Build security in from the first design doc — least privilege, fail-closed defaults, validated inputs — rather than bolting it on.",
                "real_world": [
                    ["CISA Secure by Design (2023)", "US and international agencies urged vendors to make products secure by default."],
                ],
                "analogy": "Designing a building with fire exits, not adding them after the first fire.",
                "math": "defence in depth: P(breach) = Π P(each independent layer fails)",
                "code": "# CAMEL Sentinel defaults\nuser text -> role='user' only · tools allow-listed · non-root container\nsecrets at run time · PII redacted · outputs checked",
                "in_project": "Allow-listed tools, server-side system prompt, non-root image, .dockerignore, plausibility checks.",
                "security": "The lesson of the whole AI Security Lab.",
            },
            {
                "id": "production_ready", "name": "Production readiness",
                "oneliner": "Tests, monitoring, drift detection, rollback, documentation and cost controls — what turns a demo into a service.",
                "real_world": [
                    ["Google's ML Test Score (2017)", "a rubric of tests and monitoring for production ML readiness."],
                ],
                "analogy": "A car is not road-ready because the engine starts — it needs brakes, lights, mirrors and a service schedule.",
                "math": "drift: PSI > 0.25 ⇒ investigate / retrain;  SLO: availability ≥ 99.9 %",
                "code": "HEALTHCHECK CMD curl -fsS http://localhost:8000/health\n# plus: pinned deps, model card, time-holdout validation, image tags + digests",
                "in_project": "Health checks, time-holdout validation, model card, versioned images (v1.0, v2.0), runbook in docs/06.",
                "security": "Monitoring is also detection — the SOC watches the same signals.",
            },
        ],
    },
]
