"""
camel_sentinel.gnn — GNN-based fraud detection module (Phase 10).

Self-contained heterogeneous graph neural network demonstration that answers:
"How can a GNN detect fraud by learning not only from transaction features,
but also from relationships among customers, accounts, merchants, and devices?"

SYNTHETIC DEMONSTRATION — not trained on real customer transaction data.
All data is generated by synthetic_data.py with deliberately planted fraud
patterns designed to illustrate both tabular and relational fraud signals.
"""
